CREATE DATABASE ConnectPlus;
GO

CREATE TABLE TipoDeContato(
TipoDeContatoID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
Titulo VARCHAR(100) NOT NULL
);
GO

CREATE TABLE Contato(
IdContato UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
Nome VARCHAR(100) NOT NULL,
formaDeContato VARCHAR(256) UNIQUE NOT NULL,
Imagem VARCHAR(100) NOT NULL,
tipoDeContato VARCHAR(256) UNIQUE NOT NULL,
IdTipoContato UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TipoDeContato(TipoDeContatoID)
);
